-- イベント2（箱根温泉リゾート）用のオプションデータを作成

-- オプションカテゴリーを作成
INSERT OR IGNORE INTO option_categories (id, name, event_id, enable_flg) VALUES 
(1, '追加サービス', 2, 1);

-- オプションを作成
INSERT OR IGNORE INTO options (id, name, event_id, category_id, enable_flg) VALUES 
(1, '貸切露天風呂 60分', 2, 1, 1),
(2, '夕食グレードアップ（特選会席）', 2, 1, 1),
(3, '朝食ルームサービス', 2, 1, 1);

-- オプション価格を作成（各オプションは1つの在庫のみ）
INSERT OR IGNORE INTO option_prices (option_id, stock_name, price, display_order) VALUES 
(1, '貸切露天風呂', 5000, 1),
(2, '特選会席', 3000, 1),
(3, 'ルームサービス', 1500, 1);

-- オプション在庫を作成（2026年4月1日〜5月31日、毎日）
-- 貸切露天風呂（1日5組まで）
INSERT OR IGNORE INTO option_stocks (option_id, date, stock, booked, stock_name, price, total_stock, available_stock, enable_flg)
SELECT 
  1,
  date(start_date, '+' || seq || ' days'),
  5,
  0,
  '貸切露天風呂',
  5000,
  5,
  5,
  1
FROM 
  (SELECT '2026-04-01' as start_date),
  (SELECT 0 as seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL 
   SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
   SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL 
   SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
   SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL 
   SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL
   SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL 
   SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
   SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL 
   SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL
   SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL 
   SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL
   SELECT 60)
WHERE date(start_date, '+' || seq || ' days') <= '2026-05-31';

-- 夕食グレードアップ（1日20組まで）
INSERT OR IGNORE INTO option_stocks (option_id, date, stock, booked, stock_name, price, total_stock, available_stock, enable_flg)
SELECT 
  2,
  date(start_date, '+' || seq || ' days'),
  20,
  0,
  '特選会席',
  3000,
  20,
  20,
  1
FROM 
  (SELECT '2026-04-01' as start_date),
  (SELECT 0 as seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL 
   SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
   SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL 
   SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
   SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL 
   SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL
   SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL 
   SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
   SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL 
   SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL
   SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL 
   SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL
   SELECT 60)
WHERE date(start_date, '+' || seq || ' days') <= '2026-05-31';

-- 朝食ルームサービス（1日10組まで）
INSERT OR IGNORE INTO option_stocks (option_id, date, stock, booked, stock_name, price, total_stock, available_stock, enable_flg)
SELECT 
  3,
  date(start_date, '+' || seq || ' days'),
  10,
  0,
  'ルームサービス',
  1500,
  10,
  10,
  1
FROM 
  (SELECT '2026-04-01' as start_date),
  (SELECT 0 as seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL 
   SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
   SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL 
   SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
   SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL 
   SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL
   SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL 
   SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
   SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL 
   SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL
   SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL 
   SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL
   SELECT 60)
WHERE date(start_date, '+' || seq || ' days') <= '2026-05-31';
